name: "Telegram Bot API"
description: "Self-hosted local instance of the Telegram Bot API server"
image: "ghcr.io/hanwg/telegram-bot-api/{arch}"
version: "9.4"
slug: "telegram_bot_api"
init: false
arch:
  - amd64
  - aarch64
url: "https://github.com/hanwg/hassio-apps"
ports:
  8081/tcp: 8081
  8082/tcp: null
ingress: true
ingress_port: 8082
panel_icon: mdi:history
panel_title: "Telegram Bot API Statistics"
panel_admin: true
startup: system
map:
  - media
options:
  api_id: ""
  api_hash: ""
  log_level: 1
schema:
  api_id: password
  api_hash: password
  log_level: int(1,4)
watchdog: tcp://[HOST]:[PORT:8081]