name: "Telegram Bot API"
description: "Self-hosted local instance of the Telegram Bot API server"
version: "0.1.12"
slug: "telegram_bot_api"
init: false
arch:
  - amd64
  - aarch64
url: "https://github.com/hanwg/hassio-apps"
ports:
  8081/tcp: 8081
startup: system
map:
  - media
options:
  api_id: ""
  api_hash: ""
  log_level: 1
schema:
  api_id: password
  api_hash: password
  log_level: int
watchdog: tcp://[HOST]:[PORT:8081]