name: "Telegram Bot API"
description: "Self-hosted local instance of the Telegram Bot API server"
version: "0.0.2"
slug: "telegram_bot_api"
init: false
arch:
  - i386
url: "https://github.com/hanwg/hassio-addons/tree/main/telegram-bot-api"
ports:
  8081/tcp: 8081
startup: system
map:
  - media
options:
  - api_id: ""
  - api_hash: ""
schcema:
  - api_id: str
  - api_hash: str
watchdog: tcp://[HOST]:[PORT:8081]